name: Node.js CI
on:
  push:
    branches-ignore:
      - dev
      - master

env:
  NODE_VERSION_X: "14.x"
  HASURA_VERSION: "v2.7.0"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgrespassword
        ports:
          - 5431:5431
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      graphql-engine:
        image: hasura/graphql-engine:v2.7.0
        ports:
          - 5001:5001
        env:
          DEFAULT_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5431/postgres
          HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5431/postgres
          HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
          HASURA_GRAPHQL_ADMIN_SECRET: "hasura-secret"
          HASURA_ACTION_BASE_URL: "http://localhost:8888"
          HASURA_ADMIN_SECRET: "hasura-secret"
          GRAPHQL_URL: "http://localhost:5001/v1/graphql"
    steps:
      - name: Hasura Health Check
        run: sleep 10 && curl -f http://localhost:5001/healthz

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_X }}
      - name: Get node version
        run: |
          echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install --no-progress --non-interactive --prefer-offline
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - name: install hasura cli
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=${{ env.HASURA_VERSION }} bash
